FROM osrf/ros:noetic-desktop-full

# =========================================================
# =========================================================

# Are you are looking for how to use this docker file?
#   - https://docs.openvins.com/dev-docker.html
#   - https://docs.docker.com/get-started/
#   - http://wiki.ros.org/docker/Tutorials/Docker

# =========================================================
# =========================================================

# Dependencies we use, catkin tools is very good build system
# Also some helper utilities for fast in terminal edits (nano etc)
RUN apt-get update && apt-get install -y libeigen3-dev nano git
RUN sudo apt-get install -y python3-catkin-tools python3-osrf-pycommon

# Ceres solver install and setup
RUN sudo apt-get install -y cmake libgoogle-glog-dev libgflags-dev libatlas-base-dev libeigen3-dev libsuitesparse-dev libceres-dev
# ENV CERES_VERSION="2.0.0"
# RUN git clone https://ceres-solver.googlesource.com/ceres-solver && \
#     cd ceres-solver && \
#     git checkout tags/${CERES_VERSION} && \
#     mkdir build && cd build && \
#     cmake .. && \
#     make -j$(nproc) install && \
#     rm -rf ../../ceres-solver

# Seems this has Python 3.8 installed on it...
RUN apt-get update && apt-get install -y python3-dev python3-matplotlib python3-numpy python3-psutil python3-tk

# # Install deps needed for clion remote debugging
# # https://blog.jetbrains.com/clion/2020/01/using-docker-with-clion/
# # RUN sed -i '6i\source "/catkin_ws/devel/setup.bash"\' /ros_entrypoint.sh
# RUN apt-get update && apt-get install -y ssh build-essential gcc g++ \
#     gdb clang cmake rsync tar python && apt-get clean
# RUN ( \
#     echo 'LogLevel DEBUG2'; \
#     echo 'PermitRootLogin yes'; \
#     echo 'PasswordAuthentication yes'; \
#     echo 'Subsystem sftp /usr/lib/openssh/sftp-server'; \
#   ) > /etc/ssh/sshd_config_test_clion \
#   && mkdir /run/sshd
# RUN useradd -m user && yes password | passwd user
# RUN usermod -s /bin/bash user
# CMD ["/usr/sbin/sshd", "-D", "-e", "-f", "/etc/ssh/sshd_config_test_clion"]
ENV DEBIAN_FRONTEND=noninteractive
ENV TZ=Europe/Kiev
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

RUN apt install -y tmux gedit htop terminator
RUN mkdir -p /catkin_ws/src && cd /catkin_ws/src && git clone https://github.com/rpng/open_vins.git
# Next command doesn't work somehow
# RUN apt-get update && apt-get install -y \
#     python3-catkin-tools \
#     libopencv-dev \
#     python3-opencv \
#     && rosdep update
#     RUN bash -c "source /opt/ros/noetic/setup.bash && \
#     cd /catkin_ws && \
#     catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release \
#                                    -DCMAKE_PREFIX_PATH=/usr/lib/x86_64-linux-gnu/cmake/opencv4 \
#                                    -DOpenCV_INCLUDE_DIRS=/usr/include/opencv4 && \
#     catkin build"


#RUN echo "source ~/catkin_ws/devel/setup.bash" >> ~/.bashrc
